server:
  port: 8087

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1031452900681-ibs27mg4dmlkf09vbt0as13qg0g0bm82.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "http://localhost:8087/login/oauth2/code/google"
            scope: # 기본 값 openid,profile,email => profile, email 로 설정 변경
              - profile
              - email

          kakao:
            client-id: 60ac35d59e973175afc8d85d80eecff8
            client-secret: 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
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: # https://developers.kakao.com/docs/latest/ko/kakaologin/common#user-info
              - profile_nickname
              - profile_image
              - account_email
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            client-name: Kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: header
            user-name-attribute: id # Kakao 응답 값 id, connected_at, properties, kakao_account 중 id 지정

  datasource:
    url: jdbc:mysql://localhost:3306/dulumi
    username: root
    password: 10061
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    elasticsearch:
      uris: http://localhost:9200
      username: elastic

jwt:
  secret: HZwx7wgZ071R2n0sQB1dzdSvSwaXUjQFVfmyodvd
  access_token_expire_time: 1800000




logging:
  level:
    root: INFO
    com.example.dulumi: DEBUG



